{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.untitled30310",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3760049,
          "sha512": "ad3eb29e1d2aca54d449fada4a45b6a30a85ff8e59fd80fe4fb01bd0cc6c738a2d433fd27c84d681ac3cabea88097f496c229f4b66b09a7ca5436955fdfb3ac5",
          "sha256": "f672fc640462ac8a0f9be80e13640a8fce57740f5daf83065717acbfae4258b3",
          "sha1": "1bd22775fb0aa1270317773fa34ccd3c60fbd833",
          "md5": "f6487e8e8503b076bf3bcd2b834b9b29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-3316dd8728419ad3534e3f6112aa6291f587078a"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3760049,
          "sha512": "ad3eb29e1d2aca54d449fada4a45b6a30a85ff8e59fd80fe4fb01bd0cc6c738a2d433fd27c84d681ac3cabea88097f496c229f4b66b09a7ca5436955fdfb3ac5",
          "sha256": "f672fc640462ac8a0f9be80e13640a8fce57740f5daf83065717acbfae4258b3",
          "sha1": "1bd22775fb0aa1270317773fa34ccd3c60fbd833",
          "md5": "f6487e8e8503b076bf3bcd2b834b9b29"
        }
      ]
    }
  ]
}
