{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.untitled30712",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3874609,
          "sha512": "b8ba6315c1260fb08ca41681629c1f2442264b76fde48bfe76b02efc35e45ea92c9eb2dd7e9014e27f783ed4e3ea15a033188d8c5b6504f8089a6f530b60a207",
          "sha256": "e65841b2742c41f7638063ea90ae80d86ed2fe581107a5ab28bb6e240a1fd45f",
          "sha1": "1b19a4137f0ab4c7f5b7042bbdd9054c82f5fecb",
          "md5": "e0982cbb5f56a30275cea1770b6e5d06"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3874609,
          "sha512": "b8ba6315c1260fb08ca41681629c1f2442264b76fde48bfe76b02efc35e45ea92c9eb2dd7e9014e27f783ed4e3ea15a033188d8c5b6504f8089a6f530b60a207",
          "sha256": "e65841b2742c41f7638063ea90ae80d86ed2fe581107a5ab28bb6e240a1fd45f",
          "sha1": "1b19a4137f0ab4c7f5b7042bbdd9054c82f5fecb",
          "md5": "e0982cbb5f56a30275cea1770b6e5d06"
        }
      ]
    }
  ]
}
